# Generated by Django 3.2 on 2022-07-19 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('cpf', models.CharField(max_length=14, verbose_name='Cpf')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateTimeField(auto_now=True, verbose_name='Data')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedido_clientes', to='pedidos.cliente', verbose_name='Cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=50, verbose_name='Descrição')),
                ('marca', models.CharField(max_length=30, verbose_name='Marca')),
                ('valor', models.FloatField(blank=True, null=True, verbose_name='Valor')),
                ('valor_compra', models.FloatField(blank=True, null=True, verbose_name='Valor de Compra')),
            ],
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='pedidos.produto', verbose_name='Produto')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(related_name='pedidos_itens', through='pedidos.ProdutoPedido', to='pedidos.Produto'),
        ),
    ]
