# Generated by Django 3.2 on 2022-07-19 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.FloatField(verbose_name='Valor')),
                ('quantidade', models.IntegerField(verbose_name='Quantidade')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='pedidos.pedido', verbose_name='Pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='pedidos.produto', verbose_name='Produto')),
            ],
        ),
        migrations.DeleteModel(
            name='Itens',
        ),
        migrations.AlterField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(related_name='pedidos_itens', through='pedidos.ProdutoPedido', to='pedidos.Produto'),
        ),
    ]
