# Generated by Django 3.2 on 2022-07-19 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0002_auto_20220719_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(default=None, verbose_name='Quantidade'),
            preserve_default=False,
        ),
    ]
