# Generated by Django 3.2 on 2022-07-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_produto_quantidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='quantidade',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Quantidade'),
        ),
    ]
