# Generated by Django 3.2 on 2022-07-19 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_alter_produto_quantidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='itens',
        ),
    ]
