# Generated by Django 3.2 on 2022-07-19 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0006_remove_pedido_itens'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produto',
            name='quantidade',
        ),
        migrations.AddField(
            model_name='pedido',
            name='itens',
            field=models.ManyToManyField(related_name='pedidos_itens', through='pedidos.ProdutoPedido', to='pedidos.Produto'),
        ),
    ]
