# Generated by Django 3.2 on 2022-07-19 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0007_auto_20220719_1401'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='total',
        ),
    ]
